{application,microscope,
             [{applications,[kernel,stdlib,elixir,logger,cowboy,mime]},
              {description,"A simple static web server written in Elixir"},
              {modules,['Elixir.Microscope','Elixir.Microscope.Callback',
                        'Elixir.Microscope.GenServer',
                        'Elixir.Microscope.Handler',
                        'Elixir.Microscope.IndexBuilder',
                        'Elixir.Microscope.IndexBuilder.Payload',
                        'Elixir.Microscope.Logger',
                        'Elixir.Microscope.Options',
                        'Elixir.Mix.Tasks.Microscope']},
              {registered,[]},
              {vsn,"1.3.0"}]}.
